services:
  web:
    container_name: zephyr_chat
    build: ./zephyr_chat/
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy
    command: ["streamlit", "run", "app.py"]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    networks:
      - zephyr_network

  db:
    container_name: zephyr_postgres
    image: postgres:latest
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - zephyr_network

  api:
    container_name: zephyr_api
    build: ./zephyr_api/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:8000"
    networks:
      - zephyr_network

networks:
  phi_network:
    driver: bridge
